# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 536f3536408c3edbbd4a23a01f09f5cf62001de38ee9555367fea34cb0a3df8205ad9556690d15d01b6d469e9e2ec0080e07be48788b35cee51fdb79f43fbd23

test:
  secret_key_base: 6d2b14f747e04f971af85222df27b1f9d17b94982be2d61a31509cd04514965271eaeb4ebbc1199f81799f925357b6d918c74385e2b7ce75b69b40e3ab691024

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
